### ISSUE TITLE
Doesn't work in browser

### ISSUE THREAD

**Issue by julianjohannesen** [learn-co-curriculum/redux-create-store-lab#7]
It appears that the tests are intended to be run only on the command line, but if that's NOT the case, then there needs to be some sort of start script in package.json

**Comment by maxwellbenton** [comment]
Hi @julianjohannesen,

Thank you for providing this feedback. We've updated this lab so that it will now working in the browser. The tests, starter code and expected solution have been changed and an `npm start` script has also been added so that future students will be able to see the results of their code on a webpage.

This issue helped dentify a few lessons prior to this that had similar issues. Thank you for taking the time to provide this feedback and to help improve our curriculum!
